'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=v=>{try{const u=new URL(v,location.href);return ['http:','https:','mailto:'].includes(u.protocol)?u.href:'#';}catch{return '#';}};
async function get(path,kind='json'){const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw new Error('โหลด '+path+' ไม่สำเร็จ ('+r.status+')');return kind==='json'?r.json():r.text();}
function fail(el,e){if(el)el.innerHTML='<div class="error" role="alert">ไม่สามารถโหลดเนื้อหาได้ โปรดลองโหลดหน้าใหม่ หากเปิดไฟล์จากเครื่อง ให้ใช้เว็บเซิร์ฟเวอร์ตามคู่มือ README<br><small>'+escapeHTML(e.message)+'</small></div>';}
async function markdown(el,file){const text=await get(file,'text');if(!window.marked||!window.DOMPurify){const pre=document.createElement('pre');pre.style.whiteSpace='pre-wrap';pre.textContent=text;el.replaceChildren(pre);return;}el.style.whiteSpace='';el.innerHTML=DOMPurify.sanitize(marked.parse(text),{USE_PROFILES:{html:true}});el.querySelectorAll('table').forEach(t=>{const w=document.createElement('div');w.className='table-scroll';t.before(w);w.append(t);});el.querySelectorAll('h1').forEach(h=>{const h2=document.createElement('h2');h2.innerHTML=h.innerHTML;h.replaceWith(h2);});}
$('.menu-toggle').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#sidebar').classList.contains('open')){$('#sidebar').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').focus();}});
$$('[data-print]').forEach(b=>b.addEventListener('click',()=>window.print()));
async function dashboard(){const s=await get('data/stats.json');let chart;
 function draw(){const d=s.datasets[$('#dataset').value];$('#data-notice').textContent=d.notice;$('#stats-cards').innerHTML=d.metrics.map(m=>'<div class="stat"><div class="stat-label">'+escapeHTML(m.label)+'</div><div class="stat-number">'+(m.value===null?'—':new Intl.NumberFormat('th-TH').format(m.value))+'<span class="stat-unit">'+escapeHTML(m.unit)+'</span></div><div class="stat-foot">'+escapeHTML(m.year)+'</div></div>').join('');$('#chart-title').textContent=d.trend.title;$('#chart-subtitle').textContent=d.trend.subtitle;$('#trend-limit').textContent=d.limitation;$('#trend-table').innerHTML='<table><caption>'+escapeHTML(d.trend.title)+'</caption><thead><tr><th scope="col">ปีการศึกษา</th><th scope="col">จำนวน (คน)</th></tr></thead><tbody>'+d.trend.labels.map((l,i)=>'<tr><th scope="row">'+escapeHTML(l)+'</th><td>'+escapeHTML(d.trend.values[i]??'ไม่มีข้อมูล')+'</td></tr>').join('')+'</tbody></table>';
 $('#data-source').innerHTML=escapeHTML(d.status)+'<br>ที่มา: '+escapeHTML(d.sourceLabel)+(d.sourceUrl?' · <a href="'+escapeHTML(safeURL(d.sourceUrl))+'" target="_blank" rel="noopener">รายงานการศึกษา</a>':'')+(d.trendSourceUrl?' · <a href="'+escapeHTML(safeURL(d.trendSourceUrl))+'" target="_blank" rel="noopener">รายงานสถิติจังหวัด</a>':'');
 if(window.Chart){if(chart)chart.destroy();Chart.defaults.font.family='Noto Sans Thai, sans-serif';chart=new Chart($('#trend-chart'),{type:'bar',data:{labels:d.trend.labels,datasets:[{label:'จำนวนออกกลางคัน (คน)',data:d.trend.values,backgroundColor:d.trend.values.map((_,i)=>i===d.trend.values.length-1?'#8c402a':'#d8b788'),borderRadius:5,maxBarThickness:46}]},options:{responsive:true,maintainAspectRatio:false,animation:!matchMedia('(prefers-reduced-motion: reduce)').matches,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0},grid:{color:'#eee9e1'}},x:{grid:{display:false}}}}});}else{$('#chart-fallback').hidden=false;$('.chart-wrap').hidden=true;}}
 $('#dataset').value=s.defaultDataset;$('#dataset').addEventListener('change',draw);draw();
 $('#map-note').textContent=s.map.status;$('#map-list').innerHTML=s.map.points.map(p=>'<li>'+escapeHTML(p.name)+' — '+escapeHTML(p.theme)+' (ตัวอย่าง)</li>').join('');
 if(window.L){const map=L.map('map',{scrollWheelZoom:false}).setView(s.map.center,s.map.zoom);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);tiles.on('tileerror',()=>{$('#map-note').textContent=s.map.status+' • บางส่วนของแผนที่พื้นฐานโหลดไม่ได้ โปรดใช้รายชื่อพื้นที่ประกอบ';});s.map.points.forEach(p=>{const pop=document.createElement('div');pop.textContent=p.name+' • '+p.theme+' — จุดประมาณเพื่อสาธิต';L.marker([p.lat,p.lng],{title:p.name+' (ตัวอย่าง)',alt:p.name+' (ตัวอย่าง)'}).addTo(map).bindPopup(pop);});}else{$('#map').textContent='แผนที่โหลดไม่ได้ โปรดอ่านรายชื่อพื้นที่ด้านล่าง';}}
async function knowledge(){const list=await get('data/articles.json');$('#article-select').innerHTML=list.map(a=>'<option value="'+escapeHTML(a.id)+'">'+escapeHTML(a.title)+'</option>').join('');let ticket=0;async function show(id,push=false){const item=list.find(a=>a.id===id)||list[0];$('#article-select').value=item.id;$('#article-download').href=item.file;const current=++ticket;$('#knowledge-body').innerHTML='<p class="loading">กำลังโหลดบทความ…</p>';const temp=document.createElement('article');try{await markdown(temp,item.file);if(current===ticket)$('#knowledge-body').replaceChildren(...temp.childNodes);}catch(e){if(current===ticket)fail($('#knowledge-body'),e);}if(push){const u=new URL(location.href);u.searchParams.set('article',item.id);history.pushState({},'',u);}}$('#article-select').addEventListener('change',e=>show(e.target.value,true));addEventListener('popstate',()=>show(new URLSearchParams(location.search).get('article')));await show(new URLSearchParams(location.search).get('article'));const sources=await get('data/sources.json');$('#source-registry').innerHTML=sources.map(s=>'<li><strong>'+escapeHTML(s.id)+' · '+escapeHTML(s.title)+'</strong><br>'+escapeHTML(s.author)+' ('+escapeHTML(s.year)+'). '+escapeHTML(s.note)+'<br>'+(s.url?'<a href="'+escapeHTML(safeURL(s.url))+'" target="_blank" rel="noopener">เปิดแหล่งข้อมูล</a>':'')+'</li>').join('');}
async function projects(){const list=await get('data/projects.json');$('#project-list').innerHTML=list.map(p=>'<section class="panel project-card" id="'+escapeHTML(p.id)+'"><span class="badge">'+escapeHTML(p.id)+' · ตัวอย่างเพื่อประยุกต์ใช้</span><h2>'+escapeHTML(p.title)+'</h2><p>'+escapeHTML(p.objective)+'</p><p class="small muted"><b>กลุ่มเป้าหมาย:</b> '+escapeHTML(p.target)+'</p><details><summary>กิจกรรม ผู้รับผิดชอบ และการติดตาม</summary><ul>'+p.activities.map(a=>'<li>'+escapeHTML(a)+'</li>').join('')+'</ul><p><b>เจ้าภาพที่เสนอ:</b> '+escapeHTML(p.owner)+'</p><p><b>ภาคี:</b> '+escapeHTML(p.partners)+'</p><p><b>ผลผลิต:</b> '+escapeHTML(p.output)+'</p><p><b>ผลลัพธ์:</b> '+escapeHTML(p.outcome)+'</p><p><b>ระยะเวลาเสนอ:</b> '+escapeHTML(p.duration)+'</p><p><b>ทรัพยากร:</b> '+escapeHTML(p.resources)+'</p><p><b>ตัวชี้วัด:</b> '+escapeHTML(p.indicators.join(', '))+' · SDG '+escapeHTML(p.sdg)+'</p><a href="evaluation.html">ดูนิยามและเครื่องมือประเมิน →</a></details></section>').join('');}
async function alignment(){const rows=await get('data/alignment.json');const sets=[['#alignment-level','level'],['#alignment-province','provinces'],['#alignment-agency','agencies']];sets.forEach(([selector,key])=>{const items=[...new Set(rows.flatMap(r=>r[key]))];$(selector).insertAdjacentHTML('beforeend',items.map(x=>'<option>'+escapeHTML(x)+'</option>').join(''));$(selector).addEventListener('change',draw);});function draw(){const filtered=rows.filter(r=>sets.every(([sel,key])=>$(sel).value==='all'||(Array.isArray(r[key])?r[key].includes($(sel).value):r[key]===$(sel).value)));$('#alignment-status').textContent='แสดง '+filtered.length+' ความเชื่อมโยง';$('#alignment-list').innerHTML=filtered.length?'<div class="table-scroll"><table><caption>ตารางเชื่อมโยงเป้าหมายและภารกิจ</caption><thead><tr><th>เป้าหมาย / ระดับ</th><th>ภารกิจและหน่วยงาน</th><th>กิจกรรม / พื้นที่</th><th>สถานะและหลักฐาน</th></tr></thead><tbody>'+filtered.map(r=>'<tr><td><strong>'+escapeHTML(r.goal)+'</strong><br>'+escapeHTML(r.level)+'</td><td>'+escapeHTML(r.mission)+'<br><b>'+escapeHTML(r.agencies.join(' · '))+'</b><br><span class="small">ความสัมพันธ์: '+escapeHTML(r.relationship)+'</span></td><td><a href="projects.html#'+escapeHTML(r.project)+'">'+escapeHTML(r.activity)+'</a><br>'+escapeHTML(r.provinces.join(' · '))+'<br>ติดตาม: '+escapeHTML(r.indicators)+'</td><td><span class="badge">'+escapeHTML(r.status)+'</span><p class="small">'+escapeHTML(r.evidence)+'</p><a href="'+escapeHTML(safeURL(r.url))+'">อ่านแหล่งอ้างอิง</a></td></tr>').join('')+'</tbody></table></div>':'<p class="notice">ไม่มีรายการที่ตรงกับตัวเลือกนี้ ลองเลือกทุกระดับหรือทุกพื้นที่</p>'; }draw();}
async function ecosystem(){const list=await get('data/ecosystem.json');function show(i){$$('[data-eco]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.eco===i)));const x=list[i];$('#eco-detail').innerHTML='<span class="badge">ความเชื่อมโยงที่เสนอ</span><h2 style="margin-top:14px">'+escapeHTML(x.title)+'</h2><p>'+escapeHTML(x.text)+'</p><h3>สิ่งที่ส่งต่อถึงผู้เรียน</h3><p>'+escapeHTML(x.result)+'</p><a class="button secondary" href="'+escapeHTML(x.link)+'">'+escapeHTML(x.linkLabel)+' →</a>'; }$$('[data-eco]').forEach(b=>b.addEventListener('click',()=>show(+b.dataset.eco)));show(0);}
async function evaluation(){const indicators=await get('data/indicators.json');const cats=[...new Set(indicators.map(x=>x.theme))];$('#indicator-filter').insertAdjacentHTML('beforeend',cats.map(x=>'<option>'+escapeHTML(x)+'</option>').join(''));function draw(){const list=indicators.filter(x=>$('#indicator-filter').value==='all'||x.theme===$('#indicator-filter').value);$('#indicator-list').innerHTML=list.map(x=>'<details id="'+escapeHTML(x.id)+'"><summary>'+escapeHTML(x.id+' · '+x.title)+'</summary><p class="badge">ตัวชี้วัดเสนอ · '+escapeHTML(x.baseline==null||x.target==null?'ข้อมูลฐาน/เป้าหมายยังไม่ครบ':'ค่าที่ผู้ดูแลระบุ โปรดอ่านที่มา')+'</p><dl>'+[['SDG / โครงการ',x.sdg+' / '+x.project],['นิยาม',x.definition],['ตัวตั้ง',x.numerator],['ตัวหาร',x.denominator],['สูตร / หน่วย',x.formula],['ค่าฐาน / เป้าหมาย',(x.baseline==null?'ยังไม่มีค่าฐานที่รับรอง':String(x.baseline)+(x.baselineYear?' (ปี '+x.baselineYear+')':''))+' / '+(x.target==null?'กำหนดหลังตรวจฐาน':String(x.target)+(x.targetYear?' (ปี '+x.targetYear+')':''))],['แหล่งและเครื่องมือ',x.source],['ความถี่ / ผู้รับผิดชอบ',x.frequency+' / '+x.owner],['การจำแนก',x.disaggregation],['เกณฑ์และข้อจำกัด',x.limit]].map(([k,v])=>'<dt>'+escapeHTML(k)+'</dt><dd>'+escapeHTML(v)+'</dd>').join('')+'</dl></details>').join('');}$('#indicator-filter').addEventListener('change',draw);draw();const downloads=await get('data/downloads.json');$('#download-list').innerHTML=downloads.map(d=>'<a href="'+escapeHTML(d.file)+'" download><b>'+escapeHTML(d.title)+' ↓</b><small>'+escapeHTML(d.description)+'</small></a>').join('');$('#ratio-form').addEventListener('submit',e=>{e.preventDefault();const a=$('#numerator').value,b=$('#denominator').value;const n=Number(a),d=Number(b);$('#ratio-result').textContent=a===''||b===''?'ยังคำนวณไม่ได้: กรุณากรอกทั้งสองช่อง':!Number.isSafeInteger(n)||!Number.isSafeInteger(d)||n<0||d<=0?'ยังคำนวณไม่ได้: ใช้จำนวนเต็มไม่ติดลบ และตัวหารมากกว่า 0':n>d?'พบข้อมูลไม่สอดคล้อง: ตัวตั้งมากกว่าตัวหาร โปรดตรวจประชากรและช่วงเวลา':(n/d*100).toFixed(2)+'% — คำนวณจาก '+n+' ÷ '+d+' × 100 (ยังไม่ตัดสินผลตามเป้าหมาย)';});}
async function forum(){const {giscus:c}=await get('data/site.json');const valid=c.enabled&&/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(c.repo)&&c.repoId&&c.category&&c.categoryId;if(!valid){$('#forum-status').textContent='พื้นที่สนทนายังไม่เปิดใช้งาน ผู้จัดทำกำลังเตรียมการเชื่อมต่อ GitHub Discussions ระหว่างนี้เสนอแนะได้ทางอีเมลในหน้าเกี่ยวกับผู้จัดทำ';return;}$('#forum-status').textContent='การเปิดพื้นที่สนทนาจะเชื่อมต่อบริการ Giscus และ GitHub การแสดงความคิดเห็นต้องเข้าสู่ระบบ GitHub โปรดหลีกเลี่ยงข้อมูลส่วนบุคคลของผู้เรียน';const b=$('#load-discussion');b.hidden=false;b.addEventListener('click',()=>{b.disabled=true;const script=document.createElement('script');script.src='https://giscus.app/client.js';const attrs={'data-repo':c.repo,'data-repo-id':c.repoId,'data-category':c.category,'data-category-id':c.categoryId,'data-mapping':'pathname','data-strict':'1','data-reactions-enabled':'1','data-emit-metadata':'0','data-input-position':'top','data-theme':'light','data-lang':'th','crossorigin':'anonymous'};Object.entries(attrs).forEach(([k,v])=>script.setAttribute(k,v));script.async=true;script.onerror=()=>{$('#forum-status').textContent='เชื่อมต่อพื้นที่สนทนาไม่ได้ โปรดลองโหลดหน้าใหม่';};script.onload=()=>{$('#forum-status').textContent='โหลดส่วนสนทนาแล้ว หากช่องสนทนาไม่ปรากฏ โปรดตรวจการเชื่อมต่อและการตั้งค่า Giscus';};$('#giscus-container').append(script);},{once:true});}
$$('[data-markdown]').forEach(el=>markdown(el,el.dataset.markdown).catch(e=>fail(el,e)));
const actions={index:dashboard,knowledge,projects,alignment,ecosystem,evaluation,forum};const action=actions[document.body.dataset.page];if(action)action().catch(e=>fail($('#data-notice')||$('#knowledge-body')||$('#project-list')||$('#alignment-list')||$('#eco-detail')||$('#indicator-list')||$('#forum-status'),e));



async function relatedSites(){const el=document.querySelector('[data-related-sites]');if(!el)return;try{const sites=await get('data/related-sites.json');el.innerHTML=sites.map(s=>'<section class="related-card"><span class="badge">'+escapeHTML(s.id)+' · แหล่งเรียนรู้ภายนอก</span><h3><a href="'+escapeHTML(safeURL(s.url))+'" target="_blank" rel="noopener noreferrer">'+escapeHTML(s.title)+' ↗</a></h3><p>'+escapeHTML(s.description)+'</p><ul class="resource-links">'+s.links.map(l=>'<li><a href="'+escapeHTML(safeURL(l.url))+'" target="_blank" rel="noopener noreferrer">'+escapeHTML(l.label)+' ↗</a></li>').join('')+'</ul><p class="small muted">'+escapeHTML(s.status)+'</p></section>').join('');}catch(e){fail(el,e);}}
relatedSites();
